### ISSUE TITLE
Allow periods in Ceph hostnames.

### ISSUE THREAD

**Issue by CoryMac01** [45Drives/cockpit-ceph-deploy#2]
I am trying to add new hosts for ceph deploy but for hostnames that involve a period, its not allowed. I was wondering if we could allow periods in hostnames when using ceph deploy.

![image](https://user-images.githubusercontent.com/91276224/140799349-bf91aac2-8dae-4ab9-977c-cda19b311018.png)

**Comment by markdhooper** [comment]
Should be an easy tweak, working on this now.

**Comment by markdhooper** [comment]
![image](https://user-images.githubusercontent.com/50240103/140938694-7d78c718-272a-4b3f-85b2-6a0076772de5.png)

will push momentarily.

**Comment by markdhooper** [comment]
Added, it's on the stable repo now:
rocky: https://repo.45drives.com/rhel/el8/stable/noarch/cockpit-ceph-deploy-1.0.1-7.el8.noarch.rpm
ubuntu: https://repo.45drives.com/debian/pool/main/c/cockpit-ceph-deploy/cockpit-ceph-deploy_1.0.1-7focal_all.deb
