### ISSUE TITLE
Feature Request: Arch Linux Support

### ISSUE THREAD

**Issue by sempervictus** [45Drives/cockpit-ceph-deploy#4]
Thanks for building this - very handy for small deployments or "user-accessible storage controls."
If there's bandwidth available, it would be very handy for the Arch ecosystem to have this working correctly. I have a PKGBUILD for the repo already if you would like, but i figure there's a decent amount of package-management and location-specific interface to implement for the Arch-based distributions (they're essentially the same at a low level, if it work on Arch, it should work on all of them).

**Comment by markdhooper** [comment]
the biggest roadblock to porting this to Arch is the package [ceph-ansible-45d](https://github.com/45Drives/ceph-ansible/releases/tag/v5.2.4) which took us a long time to get working with Ubuntu 20.1

Until we start shipping servers that run Arch, I don't think that we have the bandwidth available in RnD here to make this a reality.
